AWSTemplateFormatVersion: '2010-09-09'
Description: 'Task definition (Containers)'

Parameters:
  ServiceName:
    Type: String
    Description: Name of the service
  StackName:
    Type: String
    Description: For naming (stack name)
  Environment:
    Type: String
    Description: For naming (development, staging, production)
  ContainerPort:
    Type: String
    Description: Port where the container is listening to.
  ConfigBucket:
    Type: String
    Description: Configuration bucket.

Outputs:
  TaskDefinition:
    Value: !Ref TaskDefinition

Resources:

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-${Environment}-${StackName}-${AWS::Region}
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ecs-service-file-${StackName}
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                  - sns:Publish
                  - ssm:DescribeParameters
                  - ssm:GetParametersByPath
                  - kms:ListKeys
                  - kms:ListAliases
                  - kms:DescribeKey
                  - kms:ListKeyPolicies
                  - kms:GetKeyPolicy
                  - kms:GetKeyRotationStatus
                  - kms:Decrypt
                Resource:
                  - *

  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${ServiceName}-${Environment}
      RetentionInDays: 14

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      TaskRoleArn: !GetAtt TaskRole.Arn
      Family: !Sub ${ServiceName}-${Environment}
      ContainerDefinitions:
        - Name: !Sub ${ServiceName}-${Environment}
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ServiceName}-${Environment}
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: !Sub /ecs/${ServiceName}-${Environment}
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          MemoryReservation: 512
          Environment:
            - Name: AWS_REGION
              Value: !Ref AWS::Region
            - Name: CONFIG_BUCKET_NAME
              Value: !Ref ConfigBucket
            - Name: PORT
              Value: !Ref ContainerPort
