Description: |
  Deploys an ApplicationLoadBalancer
Parameters:
  Listener:
    Type: String
  TargetGroup:
    Type: String
  Priority:
    Type: String
  HTTPSListener:
    Type: String
  Path:
    Type: String
Conditions:
  CreateHTTPS: !Not [ !Equals [ !Ref HTTPSListener, "" ]]
Resources:
  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref 'TargetGroup'
      Conditions:
        - Field: path-pattern
          Values:
            - !Ref Path
      ListenerArn: !Ref 'Listener'
      Priority: !Ref 'Priority'
  HTTPSListenerRule:
    Condition: CreateHTTPS
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref 'TargetGroup'
      Conditions:
        - Field: path-pattern
          Values:
            - !Ref Path
      ListenerArn: !Ref 'HTTPSListener'
      Priority: !Ref 'Priority'
Outputs:
  ListenerArn:
    Description: ApplicationLoadBalancer Listener
    Value: !Ref ListenerRule
