AWSTemplateFormatVersion: 2010-09-09
Description: >-
  ncall resources

Transform:
- AWS::Serverless-2016-10-31

Parameters: 
    SQSName: 
      Type: String
    SecurityGroups:
      Type: CommaDelimitedList
      Description: The list of SecurityGroupIds in your Virtual Private Cloud (VPC)
    Subnets:
      Type: CommaDelimitedList
      Description: The list of SubnetIds in your Virtual Private Cloud (VPC)

Resources:
  PagerDutyWebhookQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Ref SQSName

  PagerDutySQSWehookTesting:
    Type: AWS::Serverless::Function
    Properties:
      Description: Pager Duty lambda that process messages in SQS send by API gateway Lambda
      Runtime: python3.6
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: Fn::GetAtt PagerDutyWebhookQueue.Arn
      MemorySize: 128
      Timeout: 25 # Chosen to be less than the default SQS Visibility Timeout of 30 seconds
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroups
        SubnetIds: !Ref Subnets
