AWSTemplateFormatVersion: '2010-09-09'
Description: Opsworks Template
Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  PrivateSubnet1:
    Type: String
  VpcId:
    Type: String
  Stackname:
    Type: String
  OpsWorksSecurityGroup:
    Type: String
  IcingaSecurityGroup:
    Type: String
  JenkinsSecurityGroup:
    Type: String
  VPNSecurityGroup:
    Type: String
  GitRepo:
    Type: String
    Default: git@github.com:nclouds/generalized.git
Resources:
  OpsWorksStack:
    Type: AWS::OpsWorks::Stack
    Properties:
      Name: !Ref 'Stackname'
      ServiceRoleArn: !Join ['', ['arn:aws:iam::', !Ref 'AWS::AccountId', ':role/aws-opsworks-service-role']]
      DefaultInstanceProfileArn: !Join ['', ['arn:aws:iam::', !Ref 'AWS::AccountId',
          ':instance-profile/aws-opsworks-ec2-role']]
      DefaultSshKeyName: !Ref 'KeyName'
      DefaultOs: Amazon Linux 2015.09
      DefaultRootDeviceType: ebs
      VpcId: !Ref 'VpcId'
      DefaultSubnetId: !Ref 'PrivateSubnet1'
      UseCustomCookbooks: true
      UseOpsworksSecurityGroups: false
      CustomCookbooksSource:
        Type: git
        Url: !Ref 'GitRepo'
        Revision: master
      ConfigurationManager:
        Name: Chef
        Version: '11.10'
      ChefConfiguration:
        BerkshelfVersion: 3.2.0
        ManageBerkshelf: true
  icinga:
    Type: AWS::OpsWorks::Layer
    Metadata:
      Comment: OpsWorks instances require outbound Internet access. Using DependsOn
        to make sure outbound Internet Access is estlablished before creating instances
        in this layer.
    Properties:
      StackId: !Ref 'OpsWorksStack'
      Name: icinga-servers
      Type: custom
      Shortname: !Join ['-', [!Ref 'Stackname', icinga]]
      EnableAutoHealing: 'false'
      AutoAssignElasticIps: 'false'
      AutoAssignPublicIps: 'false'
      CustomRecipes:
        Setup:
        - ops-icinga2
      CustomSecurityGroupIds:
      - !Ref 'IcingaSecurityGroup'
      - !Ref 'OpsWorksSecurityGroup'
  jenkins:
    Type: AWS::OpsWorks::Layer
    Metadata:
      Comment: OpsWorks instances require outbound Internet access. Using DependsOn
        to make sure outbound Internet Access is estlablished before creating instances
        in this layer.
    Properties:
      StackId: !Ref 'OpsWorksStack'
      Name: jenkins-servers
      Type: custom
      Shortname: !Join ['-', [!Ref 'Stackname', jenkins]]
      EnableAutoHealing: 'false'
      AutoAssignElasticIps: 'true'
      AutoAssignPublicIps: 'true'
      CustomRecipes:
        Setup:
        - ops-jenkins
      CustomSecurityGroupIds:
      - !Ref 'JenkinsSecurityGroup'
      - !Ref 'OpsWorksSecurityGroup'
  vpn:
    Type: AWS::OpsWorks::Layer
    Metadata:
      Comment: OpsWorks instances require outbound Internet access. Using DependsOn
        to make sure outbound Internet Access is estlablished before creating instances
        in this layer.
    Properties:
      StackId: !Ref 'OpsWorksStack'
      Name: vpn
      Type: custom
      Shortname: !Join ['-', [!Ref 'Stackname', vpn]]
      EnableAutoHealing: 'false'
      AutoAssignElasticIps: 'true'
      AutoAssignPublicIps: 'true'
      CustomRecipes:
        Setup:
        - ops-vpn
      CustomSecurityGroupIds:
      - !Ref 'VPNSecurityGroup'
      - !Ref 'OpsWorksSecurityGroup'
