AWSTemplateFormatVersion: '2010-09-09'
Description: 'AutoScaling Group cloudwatch alarms'
Parameters:
  ParameterResourceType:
    Description: 'Full Name of AutoScaling Group.'
    Type: String
  StackAlarmTopic:
    Description: 'Name Alarm Topic'
    Type: String

Resources:
  AutoScalingTooHighAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Group MaxSize'
      AlarmName: !Sub "${AWS::StackName}-AutoScalingTooHighAlarm"
      Namespace: 'AWS/AutoScaling'
      MetricName: GroupMaxSize
      Statistic: Average
      Period: 60
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 1
      AlarmActions:
      - Ref: StackAlarmTopic
      Dimensions:
      - Name: AutoScalingGroupName
        Value: !Ref ParameterResourceType