version: '3'
services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: goapp:compose
    container_name: goapp
    ports:
      - 8080:8080
    environment:
      AWS_ENV_PATH: ''
      AWS_REGION: 'us-east-1'
      DB_HOST: 'psql'
      # This two variables are managed by aws-env in prod
      DB_USER: demo
      DB_PASSWORD: admin123
    depends_on:
      - psql
  psql:
    image: postgres:11
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./datastore:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: demo
volumes:
  postgres-data: