version: '3'
services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: goapp:nclouds-way
    container_name: goapp
    ports:
      - 8080:8080
    environment:
      AWS_ENV_PATH: ''
      AWS_REGION: 'us-east-1'
      DB_USER: postgres
    depends_on:
      - psql
  psql:
    image: postgres:11
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./datastore:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: postgres
volumes:
  postgres-data: