AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Template to create RDS Instance DB

Parameters:
  ############# DB PARAMETERS #############
  DBInstanceName:
    Type: String
    Description: Name of the db instance (Required)
    ConstraintDescription: must define an Instance Name (Required)

  DBEngine:
    Type: String
    Description: Engine for the db instance (Required)
    ConstraintDescription: must define a valid DB Engine (Required)

  DBEngineVersion:
    Type: String
    Description: Engine version for the instance (Required)
    ConstraintDescription: must define a valid DB Engine Version (Required)

  DBdataBaseName:
    Type: String
    Description: name for the database to creates (Required)
    ConstraintDescription: must define a database name (Required)

  DBDeleteProtection:
    Type: String
    Default: false
    Description: enables or disables deletion protection on the instance
    AllowedValues: [ true, false ]

  DBInstanceClass:
    Type: String
    Description: instance class for the db instance (Required)
    ConstraintDescription: must define a valid instance class (Required)

  DBMasterUsernameSP:
    Type: String
    Description: master username for the db (Required)
    ConstraintDescription: must define a username for the database

  DBMasterPasswordSP:
    Type: String
    Description: name of the parameter store of the password (Required)
    ConstraintDescription: must define a parameter that defines DB Master Password (Required)

  DBMasterPasswordParameterStoreVersion:
    Type: Number
    Description: version number of the DB Master password parameter stored in Parameter Store (Required)
    ConstraintDescription: must define a valid version number

  DBMultiAZ:
    Type: String
    Default: false
    Description: enables or disables multi availability zones
    AllowedValues: [ true, false ]

  DBStorage:
    Type: String
    Description: Storage for the RDS database in GB
    ConstraintDescription: must define a DB Storage Size (Required)

  DBMinorVersionUpgrade:
    Type: String
    Default: false
    Description: indicates whether minor engine upgrades are applied automatically to the DB instance during the maintenance window
    AllowedValues: [ true, false ]

  DBMantainanceWindow:
    Type: String
    Description: The weekly time range during which system maintenance can occur, valid format ddd:hh24:mi-ddd:hh24:mi
    ConstraintDescription: must define DB Mantainance Window (Required)

  DBPort:
    Type: String
    Description: Port number where the db accepts connections
    ConstraintDescription: must define DB Port (Required)

  DBParameterGroup:
    Type: String
    Description: Provide a valid parameter group which the instance will be related to
    ConstraintDescription: must define a valid DB Parameter Group (Required)

  ############# VPC RELATED PARAMETERS #############
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: VPC Id where db will be created

  Subnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Valid Subnet name from the VPC

  Subnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Valid Subnet name from the VPC

  ############# TAG PARAMETERS #############
  OwnerName:
    Type: String
    Description: An arbitrary tag name for the owner of these resources

  StackName:
    Type: String
    Description: The name of the stack to which these resources belong

  Environment:
    Type: String
    Default: dev
    AllowedValues: [ prod, staging, dev, qa ]
    Description: Environment name to append to resources names and tags

Resources:

  ############# DB SECURITY GROUP #############
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group db
      GroupName: !Sub sg${OwnerName}${DBInstanceName}
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          FromPort: -1
          IpProtocol: '-1'
          ToPort: -1
      VpcId: !Ref VPCId
      Tags:
        - Key: Owner
          Value: !Ref OwnerName
        - Key: StackName
          Value: !Ref StackName
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub db-sg-${StackName}-${Environment}

  DBSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref DBSecurityGroup
      IpProtocol: tcp
      FromPort: !Ref DBPort
      ToPort: !Ref DBPort

  ############# DB SUBNET GROUP #############
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DB subnet group
      SubnetIds:
        - !Ref Subnet1
        - !Ref Subnet2
      Tags:
        - Key: Owner
          Value: !Ref OwnerName
        - Key: StackName
          Value: !Ref StackName
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub db-sbg-${StackName}-${Environment}

  ############# DECLARATION OF THE INSTANCE #############
  DBInstance:
    Type: AWS::RDS::DBInstance
    DependsOn: DBSecurityGroup
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceName
      Engine: !Ref DBEngine
      EngineVersion: !Ref DBEngineVersion
      DBName: !Ref DBdataBaseName
      DeletionProtection: !Ref DBDeleteProtection
      DBInstanceClass: !Ref DBInstanceClass
      MasterUsername: !Ref DBMasterUsernameSP
      MasterUserPassword: !Sub '{{resolve:ssm-secure:${DBMasterPasswordSP}:${DBMasterPasswordParameterStoreVersion}}}'
      MultiAZ: !Ref DBMultiAZ
      StorageType: 'gp2'
      AllocatedStorage: !Ref DBStorage
      AutoMinorVersionUpgrade: !Ref DBMinorVersionUpgrade
      PreferredMaintenanceWindow: !Ref DBMantainanceWindow
      Port: !Ref DBPort
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: false
      DBParameterGroupName: !Ref DBParameterGroup
      Tags:
        - Key: Owner
          Value: !Ref OwnerName
        - Key: StackName
          Value: !Ref StackName
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub db-sbg-${StackName}-${Environment}

Outputs:

  DBInstanceCreated:
    Description: DB instance resource created
    Value: !Ref DBInstance
