AWSTemplateFormatVersion: "2010-09-09"
Description: "Life Cycle for zero downtime ECS"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Stack"
        Parameters:
          - StackName
Parameters:
  StackName:
    Type: String
    Default: stack
    Description: "This name will be used to named the resources"
  S3BucketName:
    Type: String
    Default: ""
    Description: "Name of the S3 Bucket"
  S3Key:
    Type: String
    Default: ""
    Description: "Locaction of the Lambda code example: compute/index.zip"

Resources:
  Lambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref S3Key
      Runtime: python3.7
      Role: !GetAtt LambdaRole.Arn
      Timeout: 600
      Handler: "lambda_function.lambda_handler"
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: /
      Policies:
        - PolicyName: EC2Modify-Permissions
          PolicyDocument:
            Statement:
            - 
              Effect: Allow
              Action:
                - "ec2:DescribeImages"
                - "logs:CreateLogStream"
                - "ec2:ModifySnapshotAttribute"
                - "ec2:ModifyImageAttribute"
                - "logs:CreateLogGroup"
                - "logs:PutLogEvents"
              Resource: '*'