Description:
  ElastiCache Service for the API

Parameters:
  VPCSubnets:
    Type: List<AWS::EC2::Subnet::Id>
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC-ID of your existing Virtual Private Cloud (VPC).
  StackName:
    Type: String
    Default: demo
    Description: "This name will be used to named the resources"
  Environment:
    Type: String
    Description: "Environment platform, this parameter will be used to name the resources ."
    Default: development
    AllowedValues:
      - production
      - cproduction
      - staging
      - development
  EC2SecurityGroup:
    Type: String

Resources:

  ElastiCacheSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for the ElastiCache Service to give access to the EC2 Instances
      VpcId: !Ref VpcId
      SecurityGroupEgress:
      - CidrIp: 0.0.0.0/0
        IpProtocol: '-1'
      Tags:
        - Key: Name
          Value: !Sub ${StackName}-elasticache-ecs-sg
        - Key: StackName
          Value: !Sub ${StackName}-${Environment}
  
  SGBaseIngress:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref ElastiCacheSecurityGroup
      IpProtocol: tcp
      FromPort: 6379
      ToPort: 6379
      SourceSecurityGroupId: !Ref EC2SecurityGroup

  SubnetGroup:
      Type: "AWS::ElastiCache::SubnetGroup"
      Properties:
        CacheSubnetGroupName: Subnetgroup
        Description: Subnet group for redis
        SubnetIds: !Ref VPCSubnets
  
  ElastiCacheCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      AutoMinorVersionUpgrade: "true"
      Engine: "redis"
      CacheNodeType: "cache.t2.micro"
      CacheSubnetGroupName: !Ref SubnetGroup
      ClusterName: ECSRedisCluster
      NumCacheNodes: "1"
      # AZMode: "cross-az"
      SnapshotWindow: 00:00-01:00
      PreferredMaintenanceWindow: 'sun:01:30-sun:02:30'
      SnapshotRetentionLimit: 7
      # PreferredAvailabilityZones:
      # - "us-west-2a"
      # - "us-west-2b"
      VpcSecurityGroupIds:
        - !Ref ElastiCacheSecurityGroup
      Tags:
        - Key: StackName
          Value: !Sub ${StackName}-${Environment}
        
Outputs:
    ElastiCacheCluster:
        Description: ElasticCacheCluster Endpoint
        Value: !GetAtt ElastiCacheCluster.RedisEndpoint.Address