AWSTemplateFormatVersion: 2010-09-09
Description: >-
  ASG Rule and Permission
  Author: Shariq Rizvi

Parameters:
  LambdaFunction:
    Type: String
    Description: Lambda function Name
  StackName:
    Type: String
    Description: The name of the stack to which these resources belong

Resources:
  LambdaScheduleEC2: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "EventRule"
      Name: !Sub ${StackName}-EC2-Rule
      EventPattern:
        source: 
          - "aws.ec2"
        detail-type: 
          - "EC2 Instance State-change Notification"
        detail: 
          state: 
            - "running"
      State: "ENABLED"
      Targets:
        - Arn: !Sub ${LambdaFunction}
          Id: LambdaSchedule
          
  LambdaSchedulePermissionEC2:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Sub ${LambdaFunction}
      Principal: 'events.amazonaws.com'
      SourceArn: !Sub ${LambdaScheduleEC2.Arn}