AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Environment:
    Type: String
  ServiceName:
    Type: String
  ContainerPort:
    Type: String

Outputs:
  TaskDefinition:
    Value: !Ref TaskDefinition

Resources:
  ECSLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Ref ServiceName
      RetentionInDays: 7

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 0.5GB
      NetworkMode: awsvpc
      ExecutionRoleArn: arn:aws:iam::695292474035:role/ecsTaskExecutionRole
      Family: !Sub ${ServiceName}-${Environment}
      TaskRoleArn: !Ref Taskrole
      ContainerDefinitions:
        - Name: !Ref ServiceName
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          Image: tomcat:latest
          Environment:
            - Name: ENV_VAR_PATH
              Value: /opt/webapps
            - Name: AWS_ENV_PATH
              Value: /stage/app.config/
            - Name: AWS_REGION
              Value: !Ref "AWS::Region"

          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ServiceName
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: !Ref Environment
          MemoryReservation: 500

  Taskrole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ServiceName}-${Environment}-task
      Path: /
      AssumeRolePolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "",
              "Effect": "Allow",
              "Principal": {
                "Service": "ecs-tasks.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }
      Policies:
        - PolicyName: !Sub ${ServiceName}-${Environment}-task
          PolicyDocument: |
            {
              "Version": "2012-10-17",
              "Statement": [{
                "Effect": "Allow",
                "Action": [
                  "ecs:*",
                  "ecr:*",
                  "cloudformation:*",
                  "s3:*",
                  "kms:*",
                  "logs:*",
                  "ssm:*"
                ],
                "Resource": "*"
              }]
            }
