AWSTemplateFormatVersion: "2010-09-09"
Description: "Batch configuration"

Parameters:
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnet-IDs the existing subnets in your VPC where you want to deploy node(s).
  KeyPair:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: "Public/private key pairs allow you to securely connect to your instance after it launches"
  Environment:
    Type: String
    Description: "Environment platform, this parameter will be used to name the resources ."
    Default: development
    AllowedValues:
      - production
      - cproduction
      - staging
      - development
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC-ID of your existing Virtual Private Cloud (VPC).

Resources:
  BatchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Batch jobs security group
      VpcId: !Ref VpcId
      # Batch jobs don't require ingress connections
      # SecurityGroupIngress:
      # - IpProtocol: tcp
      #   FromPort: 0
      #   ToPort: 65535
      #   CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - CidrIp: 0.0.0.0/0
        IpProtocol: '-1'
      Tags:
        - Key: Name
          Value: !Sub BatchJobs-${Environment}-${AWS::Region}

  # Schedule Builder
  BatchComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      State: ENABLED
      ServiceRole: arn:aws:iam::083372784142:role/service-role/AWSBatchServiceRole
      ComputeEnvironmentName: !Sub ComputeEnvironment-${Environment}
      ComputeResources:
        MaxvCpus: 256
        SecurityGroupIds:
          - !Ref BatchSecurityGroup
        Type: EC2
        Subnets: !Ref SubnetIds
        MinvCpus: 0
        InstanceRole: ecsInstanceRole
        InstanceTypes:
          - optimal
        Ec2KeyPair: !Ref KeyPair
        Tags: { "Name": !Sub "BatchInstance-${Environment}" }

  BatchBuilderJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: !Sub BatchJobQueue-${Environment}
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironment
      State: ENABLED
      Priority: 1

  # Job definitions
  ScheduleBuilderJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName: !Sub schedule-builder-${Environment}
      ContainerProperties:
        Memory: 2000
        ReadonlyRootFilesystem: false
        Vcpus: 2
        Image: 083372784142.dkr.ecr.us-west-2.amazonaws.com/schedule-builder:f5a1b5877b6cf9a7462f034211cf459d3ad62ea5
