Description: >
  ECS Cluster to manage a Master-Slave Jenkins infrastructure
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC to host the Jenkins ECS cluster
  PublicSubnetsIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnet Ids to host the Aplication Load Balancer
  PrivateSubnetsIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnet Ids to host the ECS AutoScaling Group instances
  ClusterName:
    Type: String
    Description: Name for the ECS Cluster
  KeyPair:
    Description: Amazon EC2 Key Pair for the ASG launch configuration
    Type: AWS::EC2::KeyPair::KeyName
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    Default: l2-demo
    Type: String
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)
    Description: S3 bucket name for the Quick Start assets. Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    Default: L2-Demo
    Type: String
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/). It cannot start or end with a hyphen (-)
  Environment:
    Type: String
    Default: Dev
    AllowedValues: [Prod, Stage, Dev]
  StackName:
    Type: String
    Description: Stack name to prefix some resource names
Resources: 
  ALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${QSS3BucketName}/${QSS3KeyPrefix}/load-balancers.yml
      Parameters:
        VpcId: !Ref VpcId
        SubnetsIds: !Join [",", !Ref PublicSubnetsIds]
        CertificateArn: ""  
        Environment: !Ref Environment
        StackName: !Ref StackName    
      Tags:
        - Key: Environment
          Value: !Sub ${StackName}-${Environment}
  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${QSS3BucketName}/${QSS3KeyPrefix}/ecs-cluster.yml
      Parameters:
        VpcId: !Ref VpcId
        SubnetIds: !Join [",", !Ref PrivateSubnetsIds]
        ALBSecurityGroup: !GetAtt ALB.Outputs.SecurityGroupId
        ClusterName: !Ref ClusterName
        InstanceType: t2.medium
        # ECSAMI: 
        DesiredCapacity: 2
        MinSize: 1
        MaxSize: 3
        MinInstancesInService: 1
        MaxBatchSize: 2
        PauseTime: PT5M
        KeyPair: !Ref KeyPair
        Environment: !Ref Environment
        StackName: !Ref StackName
      Tags:
        - Key: Environment
          Value: !Sub ${StackName}-${Environment}
    DependsOn:
      - ALB
  Jenkins:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${QSS3BucketName}/${QSS3KeyPrefix}/services/jenkins.yml
      Parameters:
        VpcId: !Ref VpcId
        Cluster: !GetAtt ECS.Outputs.Cluster
        DesiredCount: 1
        HttpListenerArn: !GetAtt ALB.Outputs.HttpListenerArn
        HttpsListenerArn: "" #!GetAtt ALB.Outputs.HttpsListenerArn
        RepositoryName: jenkins
        MasterTag: master-v1
        SlaveTag: slave
        Environment: !Ref Environment
        StackName: !Ref StackName
      Tags:
        - Key: StackName
          Value: !Sub ${StackName}-${Environment}
    DependsOn:
      - ECS